# the version of CircleCI platform
version: 2
jobs:
  build:
    docker:
      - image: circleci/python3.7

    working_directory: ~/ci_projects

    steps:
      # 1. get the code (circleCI command)
      - checkout
      # 2. create envs and install deps
      - run:
        name: install dependencies
        command: |
          python3 -m venv env
          source venv/bin/activate
          pip install -r requirements.txt
      # 3. run linters and tests
      - run:
        name: run tests
        command: |
          source venv/bin/activate
          flake8 --exclude=venv --statistics
          pytest --verbose --cov=calc_library calc_library/test_*.py
